version: '3'
services:
  backend:
    build:
      context: .
    ports:
    - 5001:5001
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: test@123
      MYSQL_DB: two-tier
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: test@123
      MYSQL_USER: devops
      MYSQL_DATABASE: two-tier
      MYSQL_PASSWORD: devops
    volumes:
      - my-datavolume:/var/lib/mysql

volumes:
  my-datavolume:



